on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64, arm, ppc64le, s390x]
    runs-on: ubuntu-latest
    container: 
      image: rancher/dapper:v0.5.0
      env: 
        BUILDARCH: ${{ matrix.arch }}
        VERBOSE: "0"
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
    steps: 
      - uses: actions/checkout@v3
      - run: dapper ci
      - uses: actions/upload-artifact@v3
        with:
          name: k3s-root-${{ matrix.arch }}
          path: |
            dist/k3s-root-${{ matrix.arch }}.tar
            dist/k3s-root-xtables-${{ matrix.arch }}.tar
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            k3s-root-amd64.tar
            k3s-root-arm64.tar
            k3s-root-arm.tar
            k3s-root-ppc64le.tar
            k3s-root-s390x.tar
            k3s-root-xtables-amd64.tar
            k3s-root-xtables-arm64.tar
            k3s-root-xtables-arm.tar
            k3s-root-xtables-ppc64le.tar
            k3s-root-xtables-s390x.tar